# abrt-action-analyze-core
# Autogenerated from man page /usr/share/man/man1/abrt-action-analyze-core.1.gz
complete -c abrt-action-analyze-core -s c -d 'Path to a core dump'
complete -c abrt-action-analyze-core -s v -d 'Be more verbose.  Can be given multiple times'
complete -c abrt-action-analyze-core -s o -d 'Output file'
complete -c abrt-action-analyze-core -s h -l help -d 'Prints help text'

