# abrt-retrace-client
# Autogenerated from man page /usr/share/man/man1/abrt-retrace-client.1.gz
complete -c abrt-retrace-client -s v -l verbose -d 'be verbose'
complete -c abrt-retrace-client -s s -l syslog -d 'log to syslog'
complete -c abrt-retrace-client -s k -l insecure -d 'allow insecure connection to retrace server (with self-signed or expired cert…'
complete -c abrt-retrace-client -l url -d 'retrace server URL'
complete -c abrt-retrace-client -l headers -d '(debug) show received HTTP headers'
complete -c abrt-retrace-client -s d -l dir -d 'read data from ABRT problem directory'
complete -c abrt-retrace-client -s c -l core -d 'read data from coredump'
complete -c abrt-retrace-client -s l -l status-delay -d 'delay for polling operations (seconds)'
complete -c abrt-retrace-client -l no-unlink -d '(debug) do not delete temporary archive created in /tmp'
complete -c abrt-retrace-client -s t -l task -d 'ID of the task on server'
complete -c abrt-retrace-client -s p -l password -d 'password of the task on server'

