# abrt-action-install-debuginfo
# Autogenerated from man page /usr/share/man/man1/abrt-action-install-debuginfo.1.gz
complete -c abrt-action-install-debuginfo -s v -d 'Be more verbose.  Can be given multiple times'
complete -c abrt-action-install-debuginfo -s y -d 'Noninteractive, assume "Yes" to all questions'
complete -c abrt-action-install-debuginfo -l ids -d 'Path to file with list of build ids.  Default: build_ids'
complete -c abrt-action-install-debuginfo -l tmpdir -d 'Path to tmp directory.  Default: /tmp/abrt-tmp-debuginfo-RANDOM_SUFFIX'
complete -c abrt-action-install-debuginfo -l cache -d 'Path to cache directory.  Default: /var/cache/abrt-di'
complete -c abrt-action-install-debuginfo -l size_mb -d 'Default: 4096'
complete -c abrt-action-install-debuginfo -l pkgmgr -d 'Package manager to use.  Default: PackageManager from CCpp. conf or "dnf"'
complete -c abrt-action-install-debuginfo -s e -l exact -d 'Download only specified files'
complete -c abrt-action-install-debuginfo -l releasever -d 'Set specific version of Operating System'
complete -c abrt-action-install-debuginfo -l repo -d 'Glob pattern to use when searching for repositories.  Default: "*debug*"'

