# abrt-action-perform-ccpp-analysis
# Autogenerated from man page /usr/share/man/man1/abrt-action-perform-ccpp-analysis.1.gz
complete -c abrt-action-perform-ccpp-analysis -s d -l problem-dir -d 'Problem directory [Default: current directory]'
complete -c abrt-action-perform-ccpp-analysis -s h -l help -d 'Show help message'

