# createrepo_c
# Autogenerated from man page /usr/share/man/man8/createrepo_c.8.gz
complete -c createrepo_c -s V -l version
complete -c createrepo_c -s q -l quiet
complete -c createrepo_c -s v -l verbose
complete -c createrepo_c -s x -l excludes
complete -c createrepo_c -l basedir
complete -c createrepo_c -s u -l baseurl
complete -c createrepo_c -s g -l groupfile
complete -c createrepo_c -s s -l checksum
complete -c createrepo_c -s p -l pretty
complete -c createrepo_c -s d -l database
complete -c createrepo_c -l no-database
complete -c createrepo_c -l update
complete -c createrepo_c -l update-md-path
complete -c createrepo_c -l skip-stat
complete -c createrepo_c -l split
complete -c createrepo_c -s i -l pkglist
complete -c createrepo_c -s n -l includepkg
complete -c createrepo_c -l recycle-pkglist
complete -c createrepo_c -l exclude
complete -c createrepo_c -s o -l outputdir
complete -c createrepo_c -s S -l skip-symlinks
complete -c createrepo_c -l changelog-limit
complete -c createrepo_c -l unique-md-filenames
complete -c createrepo_c -l simple-md-filenames
complete -c createrepo_c -l retain-old-md
complete -c createrepo_c -l distro
complete -c createrepo_c -l content
complete -c createrepo_c -l repo
complete -c createrepo_c -l revision
complete -c createrepo_c -l set-timestamp-to-revision
complete -c createrepo_c -l read-pkgs-list
complete -c createrepo_c -l workers
complete -c createrepo_c -l xz
complete -c createrepo_c -l compress-type
complete -c createrepo_c -l general-compress-type
complete -c createrepo_c -l zck
complete -c createrepo_c -l zck-dict-dir
complete -c createrepo_c -l keep-all-metadata
complete -c createrepo_c -l discard-additional-metadata
complete -c createrepo_c -l compatibility
complete -c createrepo_c -l retain-old-md-by-age
complete -c createrepo_c -s c -l cachedir
complete -c createrepo_c -l deltas
complete -c createrepo_c -l oldpackagedirs
complete -c createrepo_c -l num-deltas
complete -c createrepo_c -l max-delta-rpm-size
complete -c createrepo_c -l local-sqlite
complete -c createrepo_c -l cut-dirs
complete -c createrepo_c -l location-prefix
complete -c createrepo_c -l repomd-checksum
complete -c createrepo_c -l error-exit-val
complete -c createrepo_c -l ignore-lock

