# dotnet-nuget-verify
# Autogenerated from man page /usr/share/man/man1/dotnet-nuget-verify.1.gz
complete -c dotnet-nuget-verify -l all -d 'Specifies that all verifications possible should be performed on the package(…'
complete -c dotnet-nuget-verify -l certificate-fingerprint -d 'Verify that the signer certificate matches with one of the specified SHA256 f…'
complete -c dotnet-nuget-verify -s v -l verbosity -d 'Sets the verbosity level of the command'
complete -c dotnet-nuget-verify -l configfile -d 'The NuGet configuration file (nuget. config) to use'
complete -c dotnet-nuget-verify -s '?' -s h -l help -d 'Prints out a description of how to use the command'

