# dotnet-list-package
# Autogenerated from man page /usr/share/man/man1/dotnet-list-package.1.gz
complete -c dotnet-list-package -l config -d 'The NuGet sources to use when searching for newer packages'
complete -c dotnet-list-package -l deprecated -d 'Displays packages that have been deprecated'
complete -c dotnet-list-package -l framework -d 'Displays only the packages applicable for the specified target framework'
complete -c dotnet-list-package -s '?' -s h -l help -d 'Prints out a description of how to use the command'
complete -c dotnet-list-package -l highest-minor -d 'Considers only the packages with a matching major version number when searchi…'
complete -c dotnet-list-package -l highest-patch -d 'Considers only the packages with a matching major and minor version numbers w…'
complete -c dotnet-list-package -l include-prerelease -d 'Considers packages with prerelease versions when searching for newer packages'
complete -c dotnet-list-package -l include-transitive -d 'Lists transitive packages, in addition to the top-level packages'
complete -c dotnet-list-package -l interactive -d 'Allows the command to stop and wait for user input or action'
complete -c dotnet-list-package -l outdated -d 'Lists packages that have newer versions available'
complete -c dotnet-list-package -s s -l source -d 'The NuGet sources to use when searching for newer packages'
complete -c dotnet-list-package -s v -l verbosity -d 'Sets the verbosity level of the command'
complete -c dotnet-list-package -l vulnerable -d 'Lists packages that have known vulnerabilities'

