# dotnet
# Autogenerated from man page /usr/share/man/man1/dotnet.1.gz
complete -c dotnet -l info -d 'Prints out detailed information about a '
complete -c dotnet -l version
complete -c dotnet -l list-runtimes -d 'Prints out a list of the installed . NET runtimes'
complete -c dotnet -l list-sdks -d 'Prints out a list of the installed . NET SDKs'
complete -c dotnet -s '?' -s h -l help -d 'Prints out a list of available commands'
complete -c dotnet -s d -l diagnostics -d 'Enables diagnostic output'
complete -c dotnet -s v -l verbosity -d 'Sets the verbosity level of the command'
complete -c dotnet -l additionalprobingpath -d 'Path containing probing policy and assemblies to probe'
complete -c dotnet -l additional-deps -d 'Path to an additional . deps. json file.  A deps'
complete -c dotnet -l roll-forward -d 'Controls how roll forward is applied to the app'
complete -c dotnet -l fx-version -d 'Version of the . NET runtime to use to run the application'
complete -c dotnet -l depsfile -d 'Path to a deps. json file.  A deps'
complete -c dotnet -l runtimeconfig -d 'Path to a runtimeconfig. json file.  A runtimeconfig'

