# dotnet-nuget-disable-source
# Autogenerated from man page /usr/share/man/man1/dotnet-nuget-disable-source.1.gz
complete -c dotnet-nuget-disable-source -l configfile -d 'The NuGet configuration file (nuget. config) to use'

