# dotnet-remove-reference
# Autogenerated from man page /usr/share/man/man1/dotnet-remove-reference.1.gz
complete -c dotnet-remove-reference -s '?' -s h -l help -d 'Prints out a description of how to use the command'
complete -c dotnet-remove-reference -s f -l framework -d 'Removes the reference only when targeting a specific framework using the TFM …'

