# dotnet-nuget-update-source
# Autogenerated from man page /usr/share/man/man1/dotnet-nuget-update-source.1.gz
complete -c dotnet-nuget-update-source -l configfile -d 'The NuGet configuration file (nuget. config) to use'
complete -c dotnet-nuget-update-source -s p -l password -d 'Password to be used when connecting to an authenticated source'
complete -c dotnet-nuget-update-source -s s -l source -d 'Path to the package source'
complete -c dotnet-nuget-update-source -l store-password-in-clear-text -d 'Enables storing portable package source credentials by disabling password enc…'
complete -c dotnet-nuget-update-source -s u -l username -d 'Username to be used when connecting to an authenticated source'
complete -c dotnet-nuget-update-source -l valid-authentication-types -d 'Comma-separated list of valid authentication types for this source'

