# dotnet-dev-certs
# Autogenerated from man page /usr/share/man/man1/dotnet-dev-certs.1.gz
complete -c dotnet-dev-certs -s c -l check -d 'Checks for the existence of the development certificate but doesn[cq]t perfor…'
complete -c dotnet-dev-certs -l clean -d 'Removes all HTTPS development certificates from the certificate store by usin…'
complete -c dotnet-dev-certs -o ep -l export-path -d 'Exports the certificate to a file so that it can be used by other tools'
complete -c dotnet-dev-certs -l format -d 'T}	T{ The public part of the certificate in PEM format.  No separate '
complete -c dotnet-dev-certs -l password -d 'T}	T{ The public and private parts of the certificate as a PFX file.  T} T{'
complete -c dotnet-dev-certs -l no-password -d 'T}	T{ The public and private parts of the certificate as a pair of files in P…'
complete -c dotnet-dev-certs -s i -l import
complete -c dotnet-dev-certs -o np -d 'Doesn[cq]t use a password for the key when exporting a certificate to PEM for…'
complete -c dotnet-dev-certs -s p -d 'Specifies the password to use: [bu] 2 When exporting the development certific…'
complete -c dotnet-dev-certs -s q -l quiet -d 'Display warnings and errors only'
complete -c dotnet-dev-certs -s t -l trust -d 'Trusts the certificate on the local machine'
complete -c dotnet-dev-certs -s v -l verbose -d 'Display debug information'

