# dotnet-nuget-add-source
# Autogenerated from man page /usr/share/man/man1/dotnet-nuget-add-source.1.gz
complete -c dotnet-nuget-add-source -l configfile -d 'The NuGet configuration file (nuget. config) to use'
complete -c dotnet-nuget-add-source -s n -l name -d 'Name of the source'
complete -c dotnet-nuget-add-source -s p -l password -d 'Password to be used when connecting to an authenticated source'
complete -c dotnet-nuget-add-source -l store-password-in-clear-text -d 'Enables storing portable package source credentials by disabling password enc…'
complete -c dotnet-nuget-add-source -s u -l username -d 'Username to be used when connecting to an authenticated source'
complete -c dotnet-nuget-add-source -l valid-authentication-types -d 'Comma-separated list of valid authentication types for this source'

