# dotnet-vstest
# Autogenerated from man page /usr/share/man/man1/dotnet-vstest.1.gz
complete -c dotnet-vstest -l Blame -d 'Runs the tests in blame mode'
complete -c dotnet-vstest -l Diag -d 'Enables verbose logs for the test platform'
complete -c dotnet-vstest -l Framework -d 'Target . NET Framework version used for test execution'
complete -c dotnet-vstest -l InIsolation -d 'Runs the tests in an isolated process.  This makes vstest. console'
complete -c dotnet-vstest -o lt -l ListTests -d 'Lists all discovered tests from the given test container'
complete -c dotnet-vstest -l logger -d 'Specify a logger for test results'
complete -c dotnet-vstest -l Parallel -d 'Run tests in parallel'
complete -c dotnet-vstest -l ParentProcessId -d 'Process ID of the parent process responsible for launching the current process'
complete -c dotnet-vstest -l Platform -d 'Target platform architecture used for test execution'
complete -c dotnet-vstest -l Port -d 'Specifies the port for the socket connection and receiving the event messages'
complete -c dotnet-vstest -l 'ResultsDirectory:<PATH>' -d 'Test results directory will be created in specified path if not exists'
complete -c dotnet-vstest -l Settings -d 'Settings to use when running tests'
complete -c dotnet-vstest -l TestAdapterPath -d 'Use custom test adapters from a given path (if any) in the test run'
complete -c dotnet-vstest -l TestCaseFilter -d 'Run tests that match the given expression'
complete -c dotnet-vstest -l Tests -d 'Run tests with names that match the provided values'
complete -c dotnet-vstest -s '?' -l Help -d 'Prints out a short help for the command'

