# dotnet-store
# Autogenerated from man page /usr/share/man/man1/dotnet-store.1.gz
complete -c dotnet-store -s f -l framework -d 'Specifies the target framework'
complete -c dotnet-store -s m -l manifest -d 'The package store manifest file is an XML file that contains the list of pack…'
complete -c dotnet-store -s r -l runtime -d 'The runtime identifier to target'
complete -c dotnet-store -l framework-version -d 'Specifies the . NET SDK version'
complete -c dotnet-store -s '?' -s h -l help -d 'Prints out a description of how to use the command'
complete -c dotnet-store -s o -l output -d 'Specifies the path to the runtime package store'
complete -c dotnet-store -l skip-optimization -d 'Skips the optimization phase'
complete -c dotnet-store -l skip-symbols -d 'Skips symbol generation'
complete -c dotnet-store -s v -l verbosity -d 'Sets the verbosity level of the command'
complete -c dotnet-store -s w -l working-dir -d 'The working directory used by the command'

