# dotnet-tool-install
# Autogenerated from man page /usr/share/man/man1/dotnet-tool-install.1.gz
complete -c dotnet-tool-install -l add-source -d 'Adds an additional NuGet package source to use during installation'
complete -c dotnet-tool-install -l configfile -d 'The NuGet configuration file (nuget. config) to use'
complete -c dotnet-tool-install -l disable-parallel -d 'Prevent restoring multiple projects in parallel'
complete -c dotnet-tool-install -l framework -d 'Specifies the target framework to install the tool for.  By default, the '
complete -c dotnet-tool-install -s g -l global -d 'Specifies that the installation is user wide'
complete -c dotnet-tool-install -s '?' -s h -l help -d 'Prints out a description of how to use the command'
complete -c dotnet-tool-install -l ignore-failed-sources -d 'Treat package source failures as warnings'
complete -c dotnet-tool-install -l interactive -d 'Allows the command to stop and wait for user input or action'
complete -c dotnet-tool-install -l local -d 'Update the tool and the local tool manifest'
complete -c dotnet-tool-install -l no-cache -d 'Do not cache packages and HTTP requests'
complete -c dotnet-tool-install -l prerelease -d 'Include prerelease packages'
complete -c dotnet-tool-install -l tool-manifest -d 'Path to the manifest file'
complete -c dotnet-tool-install -l tool-path -d 'Specifies the location where to install the Global Tool'
complete -c dotnet-tool-install -s v -l verbosity -d 'Sets the verbosity level of the command'
complete -c dotnet-tool-install -l version -d 'The version of the tool to install'

