# dotnet-watch
# Autogenerated from man page /usr/share/man/man1/dotnet-watch.1.gz
complete -c dotnet-watch -l list -d 'Lists all discovered files without starting the watcher'
complete -c dotnet-watch -l no-hot-reload -d 'Suppress hot reload for supported apps'
complete -c dotnet-watch -l non-interactive -d 'Runs dotnet watch in non-interactive mode'
complete -c dotnet-watch -l project -d 'Specifies the path of the project file to run (folder only or including the p…'
complete -c dotnet-watch -s q -l quiet -d 'Suppresses all output that is generated by the dotnet watch command except wa…'
complete -c dotnet-watch -s v -l verbose -d 'Shows verbose output for debugging'
complete -c dotnet-watch -l version -d 'Shows the version of dotnet watch'

