# dotnet-nuget-delete
# Autogenerated from man page /usr/share/man/man1/dotnet-nuget-delete.1.gz
complete -c dotnet-nuget-delete -l force-english-output -d 'Forces the application to run using an invariant, English-based culture'
complete -c dotnet-nuget-delete -s '?' -s h -l help -d 'Prints out a description of how to use the command'
complete -c dotnet-nuget-delete -l interactive -d 'Allows the command to stop and wait for user input or action'
complete -c dotnet-nuget-delete -s k -l api-key -d 'The API key for the server'
complete -c dotnet-nuget-delete -l no-service-endpoint -d 'Doesn[cq]t append [lq]api/v2/package[rq] to the source URL'
complete -c dotnet-nuget-delete -l non-interactive -d 'Doesn[cq]t prompt for user input or confirmations'
complete -c dotnet-nuget-delete -s s -l source -d 'Specifies the server URL.  Supported URLs for nuget. org include https://www'

