# dotnet-pack
# Autogenerated from man page /usr/share/man/man1/dotnet-pack.1.gz
complete -c dotnet-pack -l include-symbols -d '[bu] 2'
complete -c dotnet-pack -l include-source
complete -c dotnet-pack -s c -l configuration -d 'Defines the build configuration'
complete -c dotnet-pack -l force -d 'Forces all dependencies to be resolved even if the last restore was successful'
complete -c dotnet-pack -s '?' -s h -l help -d 'Prints out a description of how to use the command'
complete -c dotnet-pack -l interactive -d 'Allows the command to stop and wait for user input or action'
complete -c dotnet-pack -l no-build -d 'Doesn[cq]t build the project before packing'
complete -c dotnet-pack -l no-dependencies -d 'Ignores project-to-project references and only restores the root project'
complete -c dotnet-pack -l no-restore -d 'Doesn[cq]t execute an implicit restore when running the command'
complete -c dotnet-pack -l nologo -d 'Doesn[cq]t display the startup banner or the copyright message'
complete -c dotnet-pack -s o -l output -d 'Places the built packages in the directory specified'
complete -c dotnet-pack -l runtime -d 'Specifies the target runtime to restore packages for'
complete -c dotnet-pack -s s -l serviceable -d 'Sets the serviceable flag in the package.  For more information, see '
complete -c dotnet-pack -s v -l verbosity -d 'Sets the verbosity level of the command'
complete -c dotnet-pack -l version-suffix -d 'Defines the value for the VersionSuffix MSBuild property'

