# dotnet-tool-search
# Autogenerated from man page /usr/share/man/man1/dotnet-tool-search.1.gz
complete -c dotnet-tool-search -l detail -d 'Shows detailed results from the query'
complete -c dotnet-tool-search -l prerelease -d 'Includes pre-release packages'
complete -c dotnet-tool-search -l skip -d 'Specifies the number of query results to skip.  Used for pagination'
complete -c dotnet-tool-search -l take -d 'Specifies the number of query results to show.  Used for pagination'
complete -c dotnet-tool-search -s '?' -s h -l help -d 'Prints out a description of how to use the command'
complete -c dotnet-tool-search -l ------------------------------------------------------------------------------------------------------------------------------------------------------------- -d 'dotnet-format                           4. 1'
complete -c dotnet-tool-search -l -------------- -d 'dotnet-format Latest Version: 4. 1'

