# dotnet-clean
# Autogenerated from man page /usr/share/man/man1/dotnet-clean.1.gz
complete -c dotnet-clean -s c -l configuration -d 'Defines the build configuration'
complete -c dotnet-clean -s f -l framework -d 'The framework that was specified at build time'
complete -c dotnet-clean -s '?' -s h -l help -d 'Prints out a description of how to use the command'
complete -c dotnet-clean -l interactive -d 'Allows the command to stop and wait for user input or action'
complete -c dotnet-clean -l nologo -d 'Doesn[cq]t display the startup banner or the copyright message'
complete -c dotnet-clean -s o -l output -d 'The directory that contains the build artifacts to clean'
complete -c dotnet-clean -s r -l runtime -d 'Cleans the output folder of the specified runtime'
complete -c dotnet-clean -s v -l verbosity -d 'Sets the verbosity level of the command'

