# dotnet-sdk-check
# Autogenerated from man page /usr/share/man/man1/dotnet-sdk-check.1.gz
complete -c dotnet-sdk-check -l --------------------------------------------------------- -d '2. 1. 816                         Up to date.  2. 2'
complete -c dotnet-sdk-check -l ----------------------------------------------------------------------------------------- -d 'Microsoft. AspNetCore. All          2. 1'
complete -c dotnet-sdk-check -s '?' -s h -l help -d 'Prints out a description of how to use the command'

