# dotnet-sln
# Autogenerated from man page /usr/share/man/man1/dotnet-sln.1.gz
complete -c dotnet-sln -s '?' -s h -l help -d 'Prints out a description of how to use the command'
complete -c dotnet-sln -l in-root -d 'Places the projects in the root of the solution, rather than creating a solut…'
complete -c dotnet-sln -s s -l solution-folder -d 'The destination solution folder path to add the projects to'

