# dotnet-new-uninstall
# Autogenerated from man page /usr/share/man/man1/dotnet-new-uninstall.1.gz
complete -c dotnet-new-uninstall -s d -l diagnostics -d 'Enables diagnostic output.  Available since . NET SDK 7. 0. 100'
complete -c dotnet-new-uninstall -s h -l help -d 'Prints out help for the uninstall command.  Available since . NET SDK 7. 0'
complete -c dotnet-new-uninstall -s v -l verbosity -d 'Sets the verbosity level of the command'

