# dotnet-nuget-list-source
# Autogenerated from man page /usr/share/man/man1/dotnet-nuget-list-source.1.gz
complete -c dotnet-nuget-list-source -l configfile -d 'The NuGet configuration file (nuget. config) to use'
complete -c dotnet-nuget-list-source -l format -d 'The format of the list command output: Detailed (the default) and Short'

