# dotnet-new-update
# Autogenerated from man page /usr/share/man/man1/dotnet-new-update.1.gz
complete -c dotnet-new-update -l interactive -d 'Allows the command to stop and wait for user input or action'
complete -c dotnet-new-update -l add-source -d 'By default, dotnet new install uses the hierarchy of NuGet configuration file…'
complete -c dotnet-new-update -s d -l diagnostics -d 'Enables diagnostic output.  Available since . NET SDK 7. 0. 100'
complete -c dotnet-new-update -s h -l help -d 'Prints out help for the update command.  Available since . NET SDK 7. 0. 100'
complete -c dotnet-new-update -s v -l verbosity -d 'Sets the verbosity level of the command'

