# dotnet-add-package
# Autogenerated from man page /usr/share/man/man1/dotnet-add-package.1.gz
complete -c dotnet-add-package -s f -l framework -d 'Adds a package reference only when targeting a specific framework'
complete -c dotnet-add-package -s '?' -s h -l help -d 'Prints out a description of how to use the command'
complete -c dotnet-add-package -l interactive -d 'Allows the command to stop and wait for user input or action'
complete -c dotnet-add-package -s n -l no-restore -d 'Adds a package reference without performing a restore preview and compatibili…'
complete -c dotnet-add-package -l package-directory -d 'The directory where to restore the packages'
complete -c dotnet-add-package -l prerelease -d 'Allows prerelease packages to be installed.  Available since . NET Core 5 SDK'
complete -c dotnet-add-package -s s -l source -d 'The URI of the NuGet package source to use during the restore operation'
complete -c dotnet-add-package -s v -l version -d 'Version of the package.  See NuGet package versioning'

