# dotnet-tool-list
# Autogenerated from man page /usr/share/man/man1/dotnet-tool-list.1.gz
complete -c dotnet-tool-list -s g -l global -d 'Lists user-wide global tools'
complete -c dotnet-tool-list -s '?' -s h -l help -d 'Prints out a description of how to use the command'
complete -c dotnet-tool-list -l local -d 'Lists local tools for the current directory'
complete -c dotnet-tool-list -l tool-path -d 'Specifies a custom location where to find global tools'

