# dotnet-restore
# Autogenerated from man page /usr/share/man/man1/dotnet-restore.1.gz
complete -c dotnet-restore -l configfile -d 'The NuGet configuration file (nuget. config) to use'
complete -c dotnet-restore -l disable-parallel -d 'Disables restoring multiple projects in parallel'
complete -c dotnet-restore -l force -d 'Forces all dependencies to be resolved even if the last restore was successful'
complete -c dotnet-restore -l force-evaluate -d 'Forces restore to reevaluate all dependencies even if a lock file already exi…'
complete -c dotnet-restore -s '?' -s h -l help -d 'Prints out a description of how to use the command'
complete -c dotnet-restore -l ignore-failed-sources -d 'Only warn about failed sources if there are packages meeting the version requ…'
complete -c dotnet-restore -l interactive -d 'Allows the command to stop and wait for user input or action'
complete -c dotnet-restore -l lock-file-path -d 'Output location where project lock file is written'
complete -c dotnet-restore -l locked-mode -d 'Don[cq]t allow updating project lock file'
complete -c dotnet-restore -l no-cache -d 'Specifies to not cache HTTP requests'
complete -c dotnet-restore -l no-dependencies -d 'When restoring a project with project-to-project (P2P) references, restores t…'
complete -c dotnet-restore -l packages -d 'Specifies the directory for restored packages'
complete -c dotnet-restore -s r -l runtime -d 'Specifies a runtime for the package restore'
complete -c dotnet-restore -s s -l source -d 'Specifies the URI of the NuGet package source to use during the restore opera…'
complete -c dotnet-restore -l use-lock-file -d 'Enables project lock file to be generated and used with restore'
complete -c dotnet-restore -s v -l verbosity -d 'Sets the verbosity level of the command'

