# dotnet-new-install
# Autogenerated from man page /usr/share/man/man1/dotnet-new-install.1.gz
complete -c dotnet-new-install -l add-source -l nuget-source -d 'By default, dotnet new install uses the hierarchy of NuGet configuration file…'
complete -c dotnet-new-install -s d -l diagnostics -d 'Enables diagnostic output.  Available since . NET SDK 7. 0. 100'
complete -c dotnet-new-install -l force -d 'Allows installing template packages from the specified sources even if they w…'
complete -c dotnet-new-install -s h -l help -d 'Prints out help for the install command.  Available since . NET SDK 7. 0. 100'
complete -c dotnet-new-install -l interactive -d 'Allows the command to stop and wait for user input or action'
complete -c dotnet-new-install -s v -l verbosity -d 'Sets the verbosity level of the command'

