# dotnet-nuget-trust
# Autogenerated from man page /usr/share/man/man1/dotnet-nuget-trust.1.gz
complete -c dotnet-nuget-trust -s '?' -s h -l help -d 'Prints out a description of how to use the command'
complete -c dotnet-nuget-trust -l configfile -d 'The NuGet configuration file (nuget. config) to use'
complete -c dotnet-nuget-trust -s v -l verbosity -d 'Sets the verbosity level of the command'
complete -c dotnet-nuget-trust -l allow-untrusted-root -d 'Specifies if the certificate for the trusted signer should be allowed to chai…'
complete -c dotnet-nuget-trust -l owners -d 'Semicolon-separated list of trusted owners to further restrict the trust of a…'
complete -c dotnet-nuget-trust -l algorithm -d 'Specifies the hash algorithm used to calculate the certificate fingerprint'
complete -c dotnet-nuget-trust -l source-url -d 'If a source-url is provided, it must be a v3 package source URL (like https:/…'

