# dotnet-build-server
# Autogenerated from man page /usr/share/man/man1/dotnet-build-server.1.gz
complete -c dotnet-build-server -s '?' -s h -l help -d 'Prints out a description of how to use the command'
complete -c dotnet-build-server -l msbuild -d 'Shuts down the MSBuild build server'
complete -c dotnet-build-server -l razor -d 'Shuts down the Razor build server'
complete -c dotnet-build-server -l vbcscompiler -d 'Shuts down the VB/C# compiler build server'

