# dotnet-nuget-locals
# Autogenerated from man page /usr/share/man/man1/dotnet-nuget-locals.1.gz
complete -c dotnet-nuget-locals -l force-english-output -d 'Forces the application to run using an invariant, English-based culture'
complete -c dotnet-nuget-locals -s '?' -s h -l help -d 'Prints out a description of how to use the command'
complete -c dotnet-nuget-locals -s c -l clear -d 'The clear option executes a clear operation on the specified cache type'
complete -c dotnet-nuget-locals -s l -l list -d 'The list option is used to display the location of the specified cache type'

