# dotnet-tool-update
# Autogenerated from man page /usr/share/man/man1/dotnet-tool-update.1.gz
complete -c dotnet-tool-update -l add-source -d 'Adds an additional NuGet package source to use during installation'
complete -c dotnet-tool-update -l configfile -d 'The NuGet configuration file (nuget. config) to use'
complete -c dotnet-tool-update -l disable-parallel -d 'Prevent restoring multiple projects in parallel'
complete -c dotnet-tool-update -l framework -d 'Specifies the target framework to update the tool for'
complete -c dotnet-tool-update -s g -l global -d 'Specifies that the update is for a user-wide tool'
complete -c dotnet-tool-update -s '?' -s h -l help -d 'Prints out a description of how to use the command'
complete -c dotnet-tool-update -l ignore-failed-sources -d 'Treat package source failures as warnings'
complete -c dotnet-tool-update -l interactive -d 'Allows the command to stop and wait for user input or action'
complete -c dotnet-tool-update -l local -d 'Update the tool and the local tool manifest'
complete -c dotnet-tool-update -l no-cache -d 'Do not cache packages and HTTP requests'
complete -c dotnet-tool-update -l tool-manifest -d 'Path to the manifest file'
complete -c dotnet-tool-update -l tool-path -d 'Specifies the location where the global tool is installed'
complete -c dotnet-tool-update -s v -l verbosity -d 'Sets the verbosity level of the command'
complete -c dotnet-tool-update -l version -d 'The version range of the tool package to update to'

