# dotnet-nuget-push
# Autogenerated from man page /usr/share/man/man1/dotnet-nuget-push.1.gz
complete -c dotnet-nuget-push -s d -l disable-buffering -d 'Disables buffering when pushing to an HTTP(S) server to reduce memory usage'
complete -c dotnet-nuget-push -l force-english-output -d 'Forces the application to run using an invariant, English-based culture'
complete -c dotnet-nuget-push -s '?' -s h -l help -d 'Prints out a description of how to use the command'
complete -c dotnet-nuget-push -l interactive -d 'Allows the command to stop and wait for user input or action'
complete -c dotnet-nuget-push -s k -l api-key -d 'The API key for the server'
complete -c dotnet-nuget-push -s n -l no-symbols -d 'Doesn[cq]t push symbols (even if present)'
complete -c dotnet-nuget-push -l no-service-endpoint -d 'Doesn[cq]t append [lq]api/v2/package[rq] to the source URL'
complete -c dotnet-nuget-push -s s -l source -d 'Specifies the server URL'
complete -c dotnet-nuget-push -l skip-duplicate -d 'When pushing multiple packages to an HTTP(S) server, treats any 409 Conflict …'
complete -c dotnet-nuget-push -o sk -l symbol-api-key -d 'The API key for the symbol server'
complete -c dotnet-nuget-push -o ss -l symbol-source -d 'Specifies the symbol server URL'
complete -c dotnet-nuget-push -s t -l timeout -d 'Specifies the timeout for pushing to a server in seconds'

