# dotnet-new-list
# Autogenerated from man page /usr/share/man/man1/dotnet-new-list.1.gz
complete -c dotnet-new-list -l author -d 'Filters templates based on template author.  Partial match is supported'
complete -c dotnet-new-list -l columns -d 'Comma-separated list of columns to display in the output'
complete -c dotnet-new-list -l columns-all -d 'Displays all columns in the output.  Available since . NET SDK 5. 0. 300'
complete -c dotnet-new-list -s d -l diagnostics -d 'Enables diagnostic output.  Available since . NET SDK 7. 0. 100'
complete -c dotnet-new-list -s h -l help -d 'Prints out help for the list command.  Available since . NET SDK 7. 0. 100'
complete -c dotnet-new-list -l ignore-constraints -d 'Disables checking if the template meets the constraints to be run'
complete -c dotnet-new-list -o lang -l language -d 'Filters templates based on language supported by the template'
complete -c dotnet-new-list -s o -l output -d 'Location to place the generated output.  The default is the current directory'
complete -c dotnet-new-list -l project -d 'The project that the template is added to'
complete -c dotnet-new-list -l tag -d 'Filters templates based on template tags'
complete -c dotnet-new-list -l type -d 'Filters templates based on template type'
complete -c dotnet-new-list -s v -l verbosity -d 'Sets the verbosity level of the command'

