# dotnet-format
# Autogenerated from man page /usr/share/man/man1/dotnet-format.1.gz
complete -c dotnet-format -l diagnostics -d 'A space-separated list of diagnostic IDs to use as a filter when fixing code …'
complete -c dotnet-format -l severity -d 'The minimum severity of diagnostics to fix'
complete -c dotnet-format -l no-restore -d 'Doesn[cq]t execute an implicit restore before formatting'
complete -c dotnet-format -l verify-no-changes -d 'Verifies that no formatting changes would be performed'
complete -c dotnet-format -l include -d 'A space-separated list of relative file or folder paths to include in formatt…'
complete -c dotnet-format -l exclude -d 'A space-separated list of relative file or folder paths to exclude from forma…'
complete -c dotnet-format -l include-generated -d 'Formats files generated by the SDK'
complete -c dotnet-format -s v -l verbosity -d 'Sets the verbosity level'
complete -c dotnet-format -l binarylog -d 'Logs all project or solution load information to a binary log file'
complete -c dotnet-format -l report -d 'Produces a JSON report in the directory specified by <REPORT_PATH>'
complete -c dotnet-format -s h -l help -d 'Shows help and usage information'
complete -c dotnet-format -l folder -d 'Treat the <PROJECT | SOLUTION> argument as a path to a simple folder of code …'

