# dotnet-nuget-sign
# Autogenerated from man page /usr/share/man/man1/dotnet-nuget-sign.1.gz
complete -c dotnet-nuget-sign -l certificate-path -d 'Specifies the file path to the certificate to be used in signing the package'
complete -c dotnet-nuget-sign -l certificate-store-name -d 'Specifies the name of the X'
complete -c dotnet-nuget-sign -l certificate-store-location -d 'Specifies the name of the X'
complete -c dotnet-nuget-sign -l certificate-subject-name -d 'Specifies the subject name of the certificate used to search a local certific…'
complete -c dotnet-nuget-sign -l certificate-fingerprint -d 'SHA-1 fingerprint of the certificate used to search a local certificate store…'
complete -c dotnet-nuget-sign -l certificate-password -d 'Specifies the certificate password, if needed'
complete -c dotnet-nuget-sign -l hash-algorithm -d 'Hash algorithm to be used to sign the package.  Defaults to SHA256'
complete -c dotnet-nuget-sign -s o -l output -d 'Specifies the directory where the signed package should be saved'
complete -c dotnet-nuget-sign -l overwrite -d 'Indicate that the current signature should be overwritten'
complete -c dotnet-nuget-sign -l timestamp-hash-algorithm -d 'Hash algorithm to be used by the RFC 3161 timestamp server'
complete -c dotnet-nuget-sign -l timestamper -d 'URL to an RFC 3161 timestamping server'
complete -c dotnet-nuget-sign -s v -l verbosity -d 'Sets the verbosity level of the command'
complete -c dotnet-nuget-sign -s '?' -s h -l help -d 'Prints out a description of how to use the command'

