# dotnet-tool-uninstall
# Autogenerated from man page /usr/share/man/man1/dotnet-tool-uninstall.1.gz
complete -c dotnet-tool-uninstall -s g -l global -d 'Specifies that the tool to be removed is from a user-wide installation'
complete -c dotnet-tool-uninstall -s '?' -s h -l help -d 'Prints out a description of how to use the command'
complete -c dotnet-tool-uninstall -l tool-path -d 'Specifies the location where to uninstall the tool'

