# dotnet-tool-restore
# Autogenerated from man page /usr/share/man/man1/dotnet-tool-restore.1.gz
complete -c dotnet-tool-restore -l configfile -d 'The NuGet configuration file (nuget. config) to use'
complete -c dotnet-tool-restore -l add-source -d 'Adds an additional NuGet package source to use during installation'
complete -c dotnet-tool-restore -l tool-manifest -d 'Path to the manifest file'
complete -c dotnet-tool-restore -l disable-parallel -d 'Prevent restoring multiple projects in parallel'
complete -c dotnet-tool-restore -l ignore-failed-sources -d 'Treat package source failures as warnings'
complete -c dotnet-tool-restore -l no-cache -d 'Do not cache packages and http requests'
complete -c dotnet-tool-restore -l interactive -d 'Allows the command to stop and wait for user input or action'
complete -c dotnet-tool-restore -s '?' -s h -l help -d 'Prints out a description of how to use the command'
complete -c dotnet-tool-restore -s v -l verbosity -d 'Sets the verbosity level of the command'

