# dotnet-migrate
# Autogenerated from man page /usr/share/man/man1/dotnet-migrate.1.gz
complete -c dotnet-migrate -l format-report-file-json
complete -c dotnet-migrate -s h -l help
complete -c dotnet-migrate -s r -l report-file
complete -c dotnet-migrate -s s -l skip-project-references
complete -c dotnet-migrate -l skip-backup
complete -c dotnet-migrate -s t -l template-file
complete -c dotnet-migrate -s v -l sdk-package-version
complete -c dotnet-migrate -s x -l xproj-file

