# dotnet-add-reference
# Autogenerated from man page /usr/share/man/man1/dotnet-add-reference.1.gz
complete -c dotnet-add-reference -s f -l framework -d 'Adds project references only when targeting a specific framework using the TF…'
complete -c dotnet-add-reference -s '?' -s h -l help -d 'Prints out a description of how to use the command'
complete -c dotnet-add-reference -l interactive -d 'Allows the command to stop and wait for user input or action'

