# dotnet-workload
# Autogenerated from man page /usr/share/man/man1/dotnet-workload.1.gz
complete -c dotnet-workload -l info -d 'Prints out detailed information about installed workloads, including their in…'
complete -c dotnet-workload -s '?' -s h -l help -d 'Prints out a list of available commands'

