# dotnet-workload-install
# Autogenerated from man page /usr/share/man/man1/dotnet-workload-install.1.gz
complete -c dotnet-workload-install -l configfile -d 'The NuGet configuration file (nuget. config) to use'
complete -c dotnet-workload-install -l disable-parallel -d 'Prevents restoring multiple projects in parallel'
complete -c dotnet-workload-install -s '?' -s h -l help -d 'Prints out a description of how to use the command'
complete -c dotnet-workload-install -l ignore-failed-sources -d 'Treats package source failures as warnings'
complete -c dotnet-workload-install -l include-previews -d 'Allows prerelease workload manifests'
complete -c dotnet-workload-install -l interactive -d 'Allows the command to stop and wait for user input or action'
complete -c dotnet-workload-install -l no-cache -d 'Prevents caching of packages and http requests'
complete -c dotnet-workload-install -l skip-manifest-update -d 'Skip updating the workload manifests'
complete -c dotnet-workload-install -s s -l source -d 'Specifies the URI of the NuGet package source to use'
complete -c dotnet-workload-install -l temp-dir -d 'Specify the temporary directory used to download and extract NuGet packages (…'
complete -c dotnet-workload-install -s v -l verbosity -d 'Sets the verbosity level of the command'

