# dotnet-workload-search
# Autogenerated from man page /usr/share/man/man1/dotnet-workload-search.1.gz
complete -c dotnet-workload-search -s '?' -s h -l help -d 'Prints out a description of how to use the command'
complete -c dotnet-workload-search -s v -l verbosity -d 'Sets the verbosity level of the command'

