# dotnet-workload-update
# Autogenerated from man page /usr/share/man/man1/dotnet-workload-update.1.gz
complete -c dotnet-workload-update -l advertising-manifests-only -d 'Downloads advertising manifests but doesn[cq]t update any workloads'
complete -c dotnet-workload-update -l configfile -d 'The NuGet configuration file (nuget. config) to use'
complete -c dotnet-workload-update -l disable-parallel -d 'Prevents restoring multiple projects in parallel'
complete -c dotnet-workload-update -l from-previous-sdk -d 'Include workloads installed with previous SDK versions in the update'
complete -c dotnet-workload-update -s '?' -s h -l help -d 'Prints out a description of how to use the command'
complete -c dotnet-workload-update -l ignore-failed-sources -d 'Treats package source failures as warnings'
complete -c dotnet-workload-update -l include-previews -d 'Allows prerelease workload manifests'
complete -c dotnet-workload-update -l interactive -d 'Allows the command to stop and wait for user input or action'
complete -c dotnet-workload-update -l no-cache -d 'Prevents caching of packages and http requests'
complete -c dotnet-workload-update -s s -l source -d 'Specifies the URI of the NuGet package source to use'
complete -c dotnet-workload-update -l temp-dir -d 'Specify the temporary directory used to download and extract NuGet packages (…'
complete -c dotnet-workload-update -s v -l verbosity -d 'Sets the verbosity level of the command'

