# enchant
# Autogenerated from man page /usr/share/man/man1/enchant.1.gz
complete -c enchant -s a -d 'List alternatives'
complete -c enchant -s l -d 'List only the misspellings'
complete -c enchant -s L -d 'Include the line number in the output'
complete -c enchant -s v -d 'Prints the program\'s version'

