# foomatic-searchprinter
# Autogenerated from man page /usr/share/man/man1/foomatic-searchprinter.1.gz
complete -c foomatic-searchprinter -o mM
complete -c foomatic-searchprinter -o dD
complete -c foomatic-searchprinter -s h

