# foomatic-ppd-to-xml
# Autogenerated from man page /usr/share/man/man1/foomatic-ppd-to-xml.1.gz
complete -c foomatic-ppd-to-xml -s d -d 'Comma-separated list of drivers with which the printer works'
complete -c foomatic-ppd-to-xml -s r -d 'Recommended driver'
complete -c foomatic-ppd-to-xml -s p -d 'Comma-separated list of known Page Description Languages (PDLs) which the pri…'
complete -c foomatic-ppd-to-xml -s l -d 'Add a link to the PPD file to the driver entry in the XML file'
complete -c foomatic-ppd-to-xml -s b -d 'Base directory for a relative link to the PPD'
complete -c foomatic-ppd-to-xml -s D -d 'Add only the driver requested by -d and -r to the driver list in the XML file…'
complete -c foomatic-ppd-to-xml -s c -d 'Add the given comment to the comment field of the XML file'
complete -c foomatic-ppd-to-xml -s C -d 'Suppress any default comments (max paper width, pages per minute, automatical…'
complete -c foomatic-ppd-to-xml -s f -d 'Directory in which to write the resulting XML file'
complete -c foomatic-ppd-to-xml -s n -d 'Do not write modified versions of existing XML files, only create XML files f…'
complete -c foomatic-ppd-to-xml -s x -d 'Create XML files independent of whether or not there are already XML files fo…'

