# ipmidetect
# Autogenerated from man page /usr/share/man/man8/ipmidetect.8.gz
complete -c ipmidetect -s h -l hostname -d 'server hostname (default=localhost)'
complete -c ipmidetect -s p -l port -d 'server port (default=8649)'
complete -c ipmidetect -s d -l detected -d 'List only detected nodes'
complete -c ipmidetect -s u -l undetected -d 'List only undetected nodes'
complete -c ipmidetect -s q -l hostrange -d 'List nodes in hostrange format (default)'
complete -c ipmidetect -s c -l comma -d 'List nodes in comma separated list'
complete -c ipmidetect -s n -l newline -d 'List nodes in newline separated list'
complete -c ipmidetect -s s -l space -d 'List nodes in space separated list'

