# ipmi-locate
# Autogenerated from man page /usr/share/man/man8/ipmi-locate.8.gz
complete -c ipmi-locate -s '?' -l help -d 'Output a help list and exit'
complete -c ipmi-locate -l usage -d 'Output a usage message and exit'

