# ipmiping
# Autogenerated from man page /usr/share/man/man8/ipmiping.8.gz
complete -c ipmiping -s h -d 'Output help menu'
complete -c ipmiping -s V -d 'Output version'
complete -c ipmiping -s c -d 'Stop after sending  count packets'
complete -c ipmiping -s i -d 'Wait  interval seconds between sending each packet'
complete -c ipmiping -s I -d 'Set source address to specified interface address'
complete -c ipmiping -s t -d 'Time to wait for a response, in seconds.  Default is five seconds'
complete -c ipmiping -s v -d 'Verbose output'
complete -c ipmiping -s s -d 'Specify an initial starting sequence number'
complete -c ipmiping -s d -d 'Turn on debugging'

