# kbuildsycoca4
# Autogenerated from man page /usr/share/man/man8/kbuildsycoca4.8.gz
complete -c kbuildsycoca4 -l nosignal -d 'Do not signal applications to update'
complete -c kbuildsycoca4 -l noincremental -d 'Disable incremental update, re-read everything'
complete -c kbuildsycoca4 -l checkstamps -d 'Check file timestamps'
complete -c kbuildsycoca4 -l nocheckfiles -d 'Disable checking files (dangerous)'
complete -c kbuildsycoca4 -l global -d 'Create global database'
complete -c kbuildsycoca4 -l menutest -d 'Perform menu generation test run only'
complete -c kbuildsycoca4 -l track -d 'Track menu id for debug purposes'
complete -c kbuildsycoca4 -l help -d 'Show help about options'
complete -c kbuildsycoca4 -l help-qt -d 'Show Qt specific options'
complete -c kbuildsycoca4 -l help-kde -d 'Show KDE specific options'
complete -c kbuildsycoca4 -l help-all -d 'Show all options'
complete -c kbuildsycoca4 -l author -d 'Show author information'
complete -c kbuildsycoca4 -s v -l version -d 'Show version information'
complete -c kbuildsycoca4 -l license -d 'Show license information'

