# kcookiejar4
# Autogenerated from man page /usr/share/man/man8/kcookiejar4.8.gz
complete -c kcookiejar4 -l author
complete -c kcookiejar4 -l help
complete -c kcookiejar4 -l help-all
complete -c kcookiejar4 -l help-kde
complete -c kcookiejar4 -l help-qt
complete -c kcookiejar4 -l license
complete -c kcookiejar4 -o v--version
complete -c kcookiejar4 -l shutdown
complete -c kcookiejar4 -l remove
complete -c kcookiejar4 -l remove-all
complete -c kcookiejar4 -l reaload-config

