# kde4-config
# Autogenerated from man page /usr/share/man/man1/kde4-config.1.gz
complete -c kde4-config -l expandvars -d 'expand ${prefix} and ${exec_prefix} in output'
complete -c kde4-config -l prefix -d 'Compiled in prefix for KDE libraries'
complete -c kde4-config -l exec-prefix -d 'Compiled in exec_prefix for KDE libraries'
complete -c kde4-config -l libsuffix -d 'Compiled in library path suffix'
complete -c kde4-config -l localprefix -d 'Prefix in $HOME used to write files'
complete -c kde4-config -l version -d 'Compiled in version string for KDE libraries'
complete -c kde4-config -l types -d 'Print a list of all available KDE resource types'
complete -c kde4-config -l path -d 'Search path for the specified type'
complete -c kde4-config -l userpath -d 'User paths for the types: desktop|autostart|trash|document'
complete -c kde4-config -l install -d 'Prefix to install resource files to'

