# kded4
# Autogenerated from man page /usr/share/man/man8/kded4.8.gz
complete -c kded4 -l author
complete -c kded4 -l help
complete -c kded4 -l help-all
complete -c kded4 -l help-kde
complete -c kded4 -l help-qt
complete -c kded4 -l license
complete -c kded4 -s v -l version
complete -c kded4 -l check

