# kross
# Autogenerated from man page /usr/share/man/man1/kross.1.gz
complete -c kross -l author
complete -c kross -l help
complete -c kross -l help-all
complete -c kross -l help-kde
complete -c kross -l help-qt
complete -c kross -l license
complete -c kross -o v--version

