# meinproc4
# Autogenerated from man page /usr/share/man/man8/meinproc4.8.gz
complete -c meinproc4 -l author
complete -c meinproc4 -l help
complete -c meinproc4 -l help-all
complete -c meinproc4 -l help-kde
complete -c meinproc4 -l help-qt
complete -c meinproc4 -l license
complete -c meinproc4 -o v--version
complete -c meinproc4 -l cache
complete -c meinproc4 -l check
complete -c meinproc4 -l htdig
complete -c meinproc4 -s o -l output
complete -c meinproc4 -l stdout
complete -c meinproc4 -l stylesheet
complete -c meinproc4 -l srcdir
complete -c meinproc4 -l param

