# memtest-setup
# Autogenerated from man page /usr/share/man/man8/memtest-setup.8.gz
complete -c memtest-setup -s b -l bin -d 'Install a binary Memtest86+ image'
complete -c memtest-setup -s e -l elf -d 'Install an ELF Memtest86+ image (the default)'
complete -c memtest-setup -s h -l help -d 'Print a help message and exit'

