# mergerepo_c
# Autogenerated from man page /usr/share/man/man8/mergerepo_c.8.gz
complete -c mergerepo_c -l version
complete -c mergerepo_c -s r -l repo
complete -c mergerepo_c -l repo-prefix-search
complete -c mergerepo_c -l repo-prefix-replace
complete -c mergerepo_c -s a -l archlist
complete -c mergerepo_c -s d -l database
complete -c mergerepo_c -l no-database
complete -c mergerepo_c -s v -l verbose
complete -c mergerepo_c -s o -l outputdir
complete -c mergerepo_c -l nogroups
complete -c mergerepo_c -l noupdateinfo
complete -c mergerepo_c -l compress-type
complete -c mergerepo_c -l zck
complete -c mergerepo_c -l zck-dict-dir
complete -c mergerepo_c -l method
complete -c mergerepo_c -l all
complete -c mergerepo_c -l noarch-repo
complete -c mergerepo_c -l unique-md-filenames
complete -c mergerepo_c -l simple-md-filenames
complete -c mergerepo_c -l omit-baseurl
complete -c mergerepo_c -s k -l koji
complete -c mergerepo_c -l simple
complete -c mergerepo_c -l pkgorigins
complete -c mergerepo_c -l arch-expand
complete -c mergerepo_c -s g -l groupfile
complete -c mergerepo_c -s b -l blocked

