# modhex
# Autogenerated from man page /usr/share/man/man1/modhex.1.gz
complete -c modhex -s d -d 'Decode data (the default is to encode data)'
complete -c modhex -s h -d 'Use hex encoding for all non-modhex data'

