# modifyrepo_c
# Autogenerated from man page /usr/share/man/man8/modifyrepo_c.8.gz
complete -c modifyrepo_c -l version
complete -c modifyrepo_c -l mdtype
complete -c modifyrepo_c -l remove
complete -c modifyrepo_c -l compress
complete -c modifyrepo_c -l no-compress
complete -c modifyrepo_c -l compress-type
complete -c modifyrepo_c -s s -l checksum
complete -c modifyrepo_c -l unique-md-filenames
complete -c modifyrepo_c -l simple-md-filenames
complete -c modifyrepo_c -l verbose
complete -c modifyrepo_c -s f -l batchfile
complete -c modifyrepo_c -l new-name
complete -c modifyrepo_c -l zck
complete -c modifyrepo_c -l zck-dict-dir

