# openssl-version.1ossl
# Autogenerated from man page /usr/share/man/man1/openssl-version.1ossl.gz
complete -c 'openssl-version.1ossl' -o help -d 'Print out a usage message'
complete -c 'openssl-version.1ossl' -s a -d 'All information, this is the same as setting all the other flags'
complete -c 'openssl-version.1ossl' -s v -d 'The current OpenSSL version'
complete -c 'openssl-version.1ossl' -s b -d 'The date the current version of OpenSSL was built'
complete -c 'openssl-version.1ossl' -s o -d 'Option information: various options set when the library was built'
complete -c 'openssl-version.1ossl' -s f -d 'Compilation flags'
complete -c 'openssl-version.1ossl' -s p -d 'Platform setting'
complete -c 'openssl-version.1ossl' -s d -d '\\s-1OPENSSLDIR\\s0 setting'
complete -c 'openssl-version.1ossl' -s e -d '\\s-1ENGINESDIR\\s0 settings'
complete -c 'openssl-version.1ossl' -s m -d '\\s-1MODULESDIR\\s0 settings'
complete -c 'openssl-version.1ossl' -s r -d 'The random number generator source settings'

