# openssl-asn1parse.1ossl
# Autogenerated from man page /usr/share/man/man1/openssl-asn1parse.1ossl.gz
complete -c 'openssl-asn1parse.1ossl' -o help -d 'Print out a usage message'
complete -c 'openssl-asn1parse.1ossl' -o inform -d 'The input format; the default is \\s-1PEM\\s0'
complete -c 'openssl-asn1parse.1ossl' -o in -d 'The input file, default is standard input'
complete -c 'openssl-asn1parse.1ossl' -o out -d 'Output file to place the \\s-1DER\\s0 encoded data into'
complete -c 'openssl-asn1parse.1ossl' -o noout -d 'Don\'t output the parsed version of the input file'
complete -c 'openssl-asn1parse.1ossl' -o offset -d 'Starting offset to begin parsing, default is start of file'
complete -c 'openssl-asn1parse.1ossl' -o length -d 'Number of bytes to parse, default is until end of file'
complete -c 'openssl-asn1parse.1ossl' -s i -d 'Indents the output according to the \\*(L"depth\\*(R" of the structures'
complete -c 'openssl-asn1parse.1ossl' -o oid -d 'A file containing additional \\s-1OBJECT\\s0 IDENTIFIERs (OIDs)'
complete -c 'openssl-asn1parse.1ossl' -o dump -d 'Dump unknown data in hex format'
complete -c 'openssl-asn1parse.1ossl' -o dlimit -d 'Like -dump, but only the first num bytes are output'
complete -c 'openssl-asn1parse.1ossl' -o strparse -d 'Parse the contents octets of the \\s-1ASN. 1\\s0 object starting at offset'
complete -c 'openssl-asn1parse.1ossl' -o genstr -o genconf -d 'Generate encoded data based on string, file or both using ASN1_generate_nconf…'
complete -c 'openssl-asn1parse.1ossl' -o strictpem -d 'If this option is used then -inform will be ignored'

