# package-cleanup
# Autogenerated from man page /usr/share/man/man1/package-cleanup.1.gz
complete -c package-cleanup -l leaves -d 'List leaf nodes in the local RPM database'
complete -c package-cleanup -l orphans -d 'List installed packages which are not available from currently configured rep…'
complete -c package-cleanup -l problems -d 'List dependency problems in the local RPM database'
complete -c package-cleanup -l dupes -d 'Scan for duplicates in the local RPM database'
complete -c package-cleanup -l cleandupes -d 'Scan for duplicates in the local RPM database and clean out the older versions'

