# plasmapkg
# Autogenerated from man page /usr/share/man/man1/plasmapkg.1.gz
complete -c plasmapkg -s h -l hash -d 'Generate a SHA1 hash for the package at \\(lqpath\\(rq'
complete -c plasmapkg -s g -l global -d 'For install or remove, operates on packages installed for all users'
complete -c plasmapkg -s t -l type -d 'The type of package, e. g'
complete -c plasmapkg -s i -l install -d 'Install the package at \\(lqpath\\(rq'
complete -c plasmapkg -s u -l upgrade -d 'Upgrade the package at \\(lqpath\\(rq'
complete -c plasmapkg -s l -l list -d 'List installed packages'
complete -c plasmapkg -s r -l remove -d 'Remove the package named \\(lqname\\(rq'
complete -c plasmapkg -s p -l packageroot -d 'Absolute path to the package root'

