# qcatool
# Autogenerated from man page /usr/share/man/man1/qcatool.1.gz
complete -c qcatool -l pass -d 'Specify the password to use'
complete -c qcatool -l newpass -d 'Specify the new password to use for password change  with the key changepass …'
complete -c qcatool -l nonroots -d 'Specify additional certificates, not trusted, but which may be used in the tr…'
complete -c qcatool -l roots -d 'Specify additional certificates which can be used as trusted (root) certifica…'
complete -c qcatool -l nosys -d 'Disable use of the standard root certificates that are provided by the operat…'
complete -c qcatool -l noprompt -d 'Disable prompting for passwords/passphrases'
complete -c qcatool -l ordered -d 'If outputting certificate information fields (Distinguished Name and Subject …'
complete -c qcatool -l debug -d 'Enable additional output to aid debugging'
complete -c qcatool -l log-file -d 'Log to the specified file'
complete -c qcatool -l log-level -d 'Log at the specified level'
complete -c qcatool -l nobundle -d 'When S/MIME signing, do not bundle the signer\'s certificate chain inside the …'

