# repodiff
# Autogenerated from man page /usr/share/man/man1/repodiff.1.gz
complete -c repodiff -l repo-old -s o -d 'Add a <repoid> as an old repository'
complete -c repodiff -l repo-new -s n -d 'Add a <repoid> as a new repository.  Can be specified multiple times'
complete -c repodiff -l archlist -s a -d 'Add architectures to change the default from just comparing source packages'
complete -c repodiff -l size -s s -d 'Output additional data about the size of the changes'
complete -c repodiff -l compare-arch -d 'Normally packages are just compared based on their name, this flag makes the …'
complete -c repodiff -l simple -d 'Output a simple one line message for modified packages'
complete -c repodiff -l downgrade -d 'Split the data for modified packages between upgraded and downgraded packages'

