# reposync
# Autogenerated from man page /usr/share/man/man1/reposync.1.gz
complete -c reposync -s a -l arch -d 'Download only packages of given architectures (default is all architectures)'
complete -c reposync -l delete -d 'Delete local packages no longer present in repository'
complete -c reposync -l download-metadata -d 'Download all repository metadata'
complete -c reposync -s g -l gpgcheck -d 'Remove packages that fail GPG signature checking after downloading'
complete -c reposync -s m -l downloadcomps -d 'Also download and uncompress comps. xml'
complete -c reposync -l metadata-path -d 'Root path under which the downloaded metadata are stored'
complete -c reposync -s n -l newest-only -d 'Download only newest packages per-repo'
complete -c reposync -l norepopath -d 'Don\\(aqt add the reponame to the download path'
complete -c reposync -s p -l download-path -d 'Root path under which the downloaded repositories are stored, relative to the…'
complete -c reposync -l remote-time -d 'Try to set the timestamps of the downloaded files to those on the remote side'
complete -c reposync -l source -d 'Download only source packages'
complete -c reposync -s u -l urls -d 'Just print urls of what would be downloaded, don\\(aqt download'

