# repomanage
# Autogenerated from man page /usr/share/man/man1/repomanage.1.gz
complete -c repomanage -l old -d 'Show older packages (for a package or a stream show all versions except the n…'
complete -c repomanage -l oldonly -d 'Show older packages (same as --old, but exclude the newest packages even when…'
complete -c repomanage -l new -d 'Show newest packages. UNINDENT '
complete -c repomanage -s s -l space -d 'Print resulting set separated by space instead of newline'
complete -c repomanage -s k -l keep -d 'Limit the resulting set to newest <keep-number> packages'

