# rmcpping
# Autogenerated from man page /usr/share/man/man8/rmcpping.8.gz
complete -c rmcpping -s h -d 'Output help menu'
complete -c rmcpping -s V -d 'Output version'
complete -c rmcpping -s c -d 'Stop after sending  count packets'
complete -c rmcpping -s i -d 'Wait  interval seconds between sending each packet'
complete -c rmcpping -s I -d 'Set source address to specified interface address'
complete -c rmcpping -s t -d 'Time to wait for a response, in seconds.  Default is five seconds'
complete -c rmcpping -s v -d 'Verbose output'
complete -c rmcpping -s s -d 'Specify an initial starting sequence number'

