# rpmargs
# Autogenerated from man page /usr/share/man/man1/rpmargs.1.gz
complete -c rpmargs -s a -d 'Process all Sisyphus packages'
complete -c rpmargs -s p -d 'When processing a directory, list package names, not file names; furthermore,…'

