# rpmelfsym
# Autogenerated from man page /usr/share/man/man1/rpmelfsym.1.gz
complete -c rpmelfsym -s a -d 'Process all Sisyphus packages'
complete -c rpmelfsym -s p -d 'When processing a directory, list package names, not file names; furthermore,…'

