# rpmfile
# Autogenerated from man page /usr/share/man/man1/rpmfile.1.gz
complete -c rpmfile -s a -d 'Process all Sisyphus packages'
complete -c rpmfile -s p -d 'When processing a directory, list package names, not file names; furthermore,…'

