# sqliterepo_c
# Autogenerated from man page /usr/share/man/man8/sqliterepo_c.8.gz
complete -c sqliterepo_c -s V -l version
complete -c sqliterepo_c -s q -l quiet
complete -c sqliterepo_c -s v -l verbose
complete -c sqliterepo_c -s f -l force
complete -c sqliterepo_c -l keep-old
complete -c sqliterepo_c -l xz
complete -c sqliterepo_c -l compress-type
complete -c sqliterepo_c -l checksum
complete -c sqliterepo_c -l local-sqlite

