# yum-debug-restore
# Autogenerated from man page /usr/share/man/man1/yum-debug-restore.1.gz
complete -c yum-debug-restore -l norepos -d 'Do not dump content of enabled repos'
complete -c yum-debug-restore -l filter-types -d 'Limit package changes to specified type'
complete -c yum-debug-restore -l ignore-arch -d 'When installing package ignore architecture and install missing packages matc…'
complete -c yum-debug-restore -l install-latest -d 'When installing use the latest package of the same name and architecture'
complete -c yum-debug-restore -l output -d 'Only output list of packages which will be installed or removed'
complete -c yum-debug-restore -l remove-installonly -d 'Allow removal of install-only packages'

