# yum-config-manager
# Autogenerated from man page /usr/share/man/man1/yum-config-manager.1.gz
complete -c yum-config-manager -l help-cmd -d 'Show this help'
complete -c yum-config-manager -l add-repo -d 'Add (and enable) the repo from the specified file or url'
complete -c yum-config-manager -l dump -d 'Print dump of current configuration values to stdout'
complete -c yum-config-manager -l set-disabled -l disable -d 'Disable the specified repos (implies --save)'
complete -c yum-config-manager -l set-enabled -l enable -d 'Enable the specified repos (implies --save)'
complete -c yum-config-manager -l save -d 'Save the current options (useful with --setopt)'
complete -c yum-config-manager -l setopt -d 'Set a configuration option'

