# yumdownloader
# Autogenerated from man page /usr/share/man/man1/yumdownloader.1.gz
complete -c yumdownloader -l help-cmd -d 'Show this help'
complete -c yumdownloader -l arch -d 'Limit the query to packages of given architectures (default is all compatible…'
complete -c yumdownloader -l source -d 'Download the source rpm'
complete -c yumdownloader -l debuginfo -d 'Download the debuginfo rpm'
complete -c yumdownloader -l downloaddir -d 'Download directory, default is the current directory (the directory must exis…'
complete -c yumdownloader -l url -d 'Instead of downloading, print list of urls where the rpms can be downloaded'
complete -c yumdownloader -l urlprotocol -d 'Limit the protocol of the urls output by the --url option'
complete -c yumdownloader -l resolve -d 'Resolves dependencies of specified packages and downloads missing dependencie…'
complete -c yumdownloader -l alldeps -d 'When used with --resolve, download all dependencies (do not skip already inst…'
complete -c yumdownloader -l forcearch

